[package]
name = "journalstat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
systemd = "0.10.0"
structopt = "0.3.26"
tabled = "0.10.0"

[profile.release]
lto = true
